# Generated by Django 4.2.13 on 2024-08-13 12:46

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0004_remove_ad_upload_alter_ad_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
