# Generated by Django 4.2.13 on 2024-08-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0005_ad_upload_alter_ad_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='upload',
        ),
        migrations.AddField(
            model_name='ad',
            name='responses',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('NE', 'Новый'), ('YE', 'Одобрен'), ('NO', 'Отклонен')], default='NE', max_length=2, verbose_name='Статус отклика'),
        ),
    ]
