# Generated by Django 4.2.13 on 2024-08-14 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0006_remove_ad_upload_ad_responses_alter_response_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='responses',
        ),
        migrations.AlterField(
            model_name='response',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='billboard.ad'),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('YES', 'Одобрен'), ('NO', 'Отклонен')], default='NEW', max_length=3, verbose_name='Статус отклика'),
        ),
    ]
