# Generated by Django 4.2.13 on 2024-08-15 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billboard', '0008_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='ad',
        ),
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to=settings.AUTH_USER_MODEL),
        ),
    ]
