# Generated by Django 4.2.13 on 2024-08-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0010_remove_subscription_email_alter_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
