# Generated by Django 4.2.13 on 2024-08-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0012_remove_subscription_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
