# Generated by Django 4.2.13 on 2024-08-16 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billboard', '0013_alter_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор отклика'),
        ),
        migrations.AlterField(
            model_name='response',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика'),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
