# Generated by Django 4.2.13 on 2024-08-16 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='code',
            field=models.CharField(default='2017', max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
